// <auto-generated />
using System;
using System.Collections.Generic;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(MangaLibraryDbContext))]
    [Migration("20251009124351_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Manga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("AdultContent")
                        .HasColumnType("boolean")
                        .HasColumnName("adultContent");

                    b.Property<string>("BannerImage")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("banner");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("countryOfOrigin");

                    b.Property<string>("Cover")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("cover");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Format")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("format");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<int?>("ReleaseDay")
                        .HasColumnType("integer")
                        .HasColumnName("releaseDay");

                    b.Property<int?>("ReleaseMonth")
                        .HasColumnType("integer")
                        .HasColumnName("releaseMonth");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("releaseYear");

                    b.Property<List<MangaStaff>>("Staff")
                        .HasColumnType("jsonb")
                        .HasColumnName("staff");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("TitleNative")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("titleNative");

                    b.HasKey("Id");

                    b.ToTable("mangas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
