export const mangaTags = [
  '4-koma',
  'Achromatic',
  'Achronological Order',
  'Acrobatics',
  'Acting',
  'Adoption',
  'Advertisement',
  'Afterlife',
  'Age Gap',
  'Age Regression',
  'Agender',
  'Agriculture',
  'Ahegao',
  'Airsoft',
  'Alchemy',
  'Aliens',
  'Alternate Universe',
  'American Football',
  'Amnesia',
  'Amputation',
  'Anachronism',
  'Anal Sex',
  'Ancient China',
  'Angels',
  'Animals',
  'Anthology',
  'Anthropomorphism',
  'Anti-Hero',
  'Archery',
  'Armpits',
  'Aromantic',
  'Arranged Marriage',
  'Artificial Intelligence',
  'Asexual',
  'Ashikoki',
  'Asphyxiation',
  'Assassins',
  'Astronomy',
  'Athletics',
  'Augmented Reality',
  'Autobiographical',
  'Aviation',
  'Badminton',
  'Ballet',
  'Band',
  'Bar',
  'Baseball',
  'Basketball',
  'Battle Royale',
  'Biographical',
  'Bisexual',
  'Blackmail',
  'Board Game',
  'Boarding School',
  'Body Horror',
  'Body Image',
  'Body Swapping',
  'Bondage',
  'Boobjob',
  'Bowling',
  'Boxing',
  "Boys' Love",
  'Bullying',
  'Butler',
  'CGI',
  'Calligraphy',
  'Camping',
  'Cannibalism',
  'Card Battle',
  'Cars',
  'Centaur',
  'Cervix Penetration',
  'Cheating',
  'Cheerleading',
  'Chibi',
  'Chimera',
  'Chuunibyou',
  'Circus',
  'Class Struggle',
  'Classic Literature',
  'Classical Music',
  'Clone',
  'Coastal',
  'Cohabitation',
  'College',
  'Coming of Age',
  'Conspiracy',
  'Cosmic Horror',
  'Cosplay',
  'Cowboys',
  'Creature Taming',
  'Crime',
  'Criminal Organization',
  'Crossdressing',
  'Crossover',
  'Cult',
  'Cultivation',
  'Cumflation',
  'Cunnilingus',
  'Curses',
  'Cute Boys Doing Cute Things',
  'Cute Girls Doing Cute Things',
  'Cyberpunk',
  'Cyborg',
  'Cycling',
  'DILF',
  'Dancing',
  'Death Game',
  'Deepthroat',
  'Defloration',
  'Delinquents',
  'Demons',
  'Denpa',
  'Desert',
  'Detective',
  'Dinosaurs',
  'Disability',
  'Dissociative Identities',
  'Double Penetration',
  'Dragons',
  'Drawing',
  'Drugs',
  'Dullahan',
  'Dungeon',
  'Dystopian',
  'E-Sports',
  'Eco-Horror',
  'Economics',
  'Educational',
  'Elderly Protagonist',
  'Elf',
  'Ensemble Cast',
  'Environmental',
  'Episodic',
  'Ero Guro',
  'Erotic Piercings',
  'Espionage',
  'Estranged Family',
  'Exhibitionism',
  'Exorcism',
  'Facial',
  'Fairy',
  'Fairy Tale',
  'Fake Relationship',
  'Family Life',
  'Fashion',
  'Feet',
  'Fellatio',
  'Female Harem',
  'Female Protagonist',
  'Femboy',
  'Femdom',
  'Fencing',
  'Filmmaking',
  'Fingering',
  'Firefighters',
  'Fishing',
  'Fisting',
  'Fitness',
  'Flat Chest',
  'Food',
  'Football',
  'Foreign',
  'Found Family',
  'Fugitive',
  'Full CGI',
  'Full Color',
  'Futanari',
  'Gambling',
  'Gangs',
  'Gender Bending',
  'Ghost',
  'Go',
  'Goblin',
  'Gods',
  'Golf',
  'Gore',
  'Group Sex',
  'Guns',
  'Gyaru',
  'Hair Pulling',
  'Handball',
  'Handjob',
  'Henshin',
  'Heterosexual',
  'Hikikomori',
  'Hip-hop Music',
  'Historical',
  'Homeless',
  'Horticulture',
  'Human Pet',
  'Hypersexuality',
  'Ice Skating',
  'Idol',
  'Impersonation',
  'Incest',
  'Indigenous Cultures',
  'Inn',
  'Inseki',
  'Irrumatio',
  'Isekai',
  'Iyashikei',
  'Jazz Music',
  'Josei',
  'Judo',
  'Kabuki',
  'Kaiju',
  'Karuta',
  'Kemonomimi',
  'Kids',
  'Kingdom Management',
  'Konbini',
  'Kuudere',
  'LGBTQ+ Themes',
  'Lacrosse',
  'Lactation',
  'Language Barrier',
  'Large Breasts',
  'Long Strip',
  'Lost Civilization',
  'Love Triangle',
  'MILF',
  'Mafia',
  'Magic',
  'Mahjong',
  'Maids',
  'Makeup',
  'Male Harem',
  'Male Pregnancy',
  'Male Protagonist',
  'Manzai',
  'Marriage',
  'Martial Arts',
  'Masochism',
  'Masturbation',
  'Matchmaking',
  'Mating Press',
  'Matriarchy',
  'Medicine',
  'Medieval',
  'Memory Manipulation',
  'Mermaid',
  'Meta',
  'Metal Music',
  'Military',
  'Mixed Gender Harem',
  'Mixed Media',
  'Modeling',
  'Monster Boy',
  'Monster Girl',
  'Mopeds',
  'Motorcycles',
  'Mountaineering',
  'Musical Theater',
  'Mythology',
  'Nakadashi',
  'Natural Disaster',
  'Necromancy',
  'Nekomimi',
  'Netorare',
  'Netorase',
  'Netori',
  'Ninja',
  'No Dialogue',
  'Noir',
  'Non-fiction',
  'Nudity',
  'Nun',
  'Office',
  'Office Lady',
  'Oiran',
  'Ojou-sama',
  'Omegaverse',
  'Orphan',
  'Otaku Culture',
  'Outdoor Activities',
  'Oyakodon',
  'POV',
  'Pandemic',
  'Parenthood',
  'Parkour',
  'Parody',
  'Pet Play',
  'Philosophy',
  'Photography',
  'Pirates',
  'Poker',
  'Police',
  'Politics',
  'Polyamorous',
  'Post-Apocalyptic',
  'Pregnancy',
  'Primarily Adult Cast',
  'Primarily Animal Cast',
  'Primarily Child Cast',
  'Primarily Female Cast',
  'Primarily Male Cast',
  'Primarily Teen Cast',
  'Prison',
  'Prostitution',
  'Proxy Battle',
  'Psychosexual',
  'Public Sex',
  'Puppetry',
  'Rakugo',
  'Rape',
  'Real Robot',
  'Rehabilitation',
  'Reincarnation',
  'Religion',
  'Rescue',
  'Restaurant',
  'Revenge',
  'Reverse Isekai',
  'Rimjob',
  'Robots',
  'Rock Music',
  'Royal Affairs',
  'Rugby',
  'Rural',
  'Sadism',
  'Samurai',
  'Satire',
  'Scat',
  'School',
  'School Club',
  'Scissoring',
  'Scuba Diving',
  'Seinen',
  'Sex Toys',
  'Shapeshifting',
  'Shimaidon',
  'Ships',
  'Shogi',
  'Shoujo',
  'Shounen',
  'Shrine Maiden',
  'Skateboarding',
  'Skeleton',
  'Slapstick',
  'Slavery',
  'Snowscape',
  'Software Development',
  'Space',
  'Space Opera',
  'Spearplay',
  'Squirting',
  'Steampunk',
  'Succubus',
  'Suicide',
  'Sumata',
  'Sumo',
  'Super Power',
  'Super Robot',
  'Superhero',
  'Surfing',
  'Surreal Comedy',
  'Survival',
  'Swapping ',
  'Sweat',
  'Swimming',
  'Swordplay',
  'Table Tennis',
  'Tanks',
  'Tanned Skin',
  'Teacher',
  "Teens' Love",
  'Tennis',
  'Tentacles',
  'Terrorism',
  'Threesome',
  'Time Loop',
  'Time Manipulation',
  'Time Skip',
  'Tokusatsu',
  'Tomboy',
  'Torture',
  'Tragedy',
  'Trains',
  'Transgender',
  'Travel',
  'Triads',
  'Tsundere',
  'Twins',
  'Unrequited Love',
  'Urban',
  'Urban Fantasy',
  'VTuber',
  'Vampire',
  'Veterinarian',
  'Video Games',
  'Vikings',
  'Villainess',
  'Virginity',
  'Virtual World',
  'Vocal Synth',
  'Volleyball',
  'Vore',
  'Voyeur',
  'War',
  'Watersports',
  'Werewolf',
  'Wilderness',
  'Witch',
  'Work',
  'Wrestling',
  'Writing',
  'Wuxia',
  'Yakuza',
  'Yandere',
  'Youkai',
  'Yuri',
  'Zombie',
  'Zoophilia',
];
