export const mangaTags = [
  'Nudity',
  'Isekai',
  'Bowling',
  'Clone',
  'Skeleton',
  'Gore',
  'Spearplay',
  'Augmented Reality',
  'Urban',
  'Goblin',
  'Proxy Battle',
  'Afterlife',
  'Tanned Skin',
  'Primarily Child Cast',
  'Achronological Order',
  'Feet',
  'Matchmaking',
  'Ballet',
  'Nun',
  'Kabuki',
  'Elderly Protagonist',
  'Transgender',
  'Go',
  'Sex Toys',
  'Advertisement',
  'Irrumatio',
  'Karuta',
  'Revenge',
  'Rock Music',
  'Filmmaking',
  'Family Life',
  'Netori',
  'Cute Boys Doing Cute Things',
  'Kemonomimi',
  'Shogi',
  'Disability',
  'Primarily Teen Cast',
  'Parkour',
  'Oiran',
  'Gambling',
  'Super Robot',
  'Vore',
  'Wuxia',
  'Swimming',
  'Agender',
  'Fashion',
  'Arranged Marriage',
  'Magic',
  'Drawing',
  'Agriculture',
  'Yakuza',
  'Fitness',
  'Detective',
  'Blackmail',
  'Full Color',
  'Primarily Adult Cast',
  'Pirates',
  'Boarding School',
  'Baseball',
  'Bullying',
  'Fisting',
  'Skateboarding',
  'Fairy Tale',
  'Archery',
  'Software Development',
  'Outdoor Activities',
  'Anachronism',
  'Super Power',
  'Dullahan',
  'Idol',
  'Public Sex',
  'Puppetry',
  'Shounen',
  'Ojou-sama',
  'Ice Skating',
  'Death Game',
  'Psychosexual',
  'Tokusatsu',
  'Natural Disaster',
  'Autobiographical',
  'American Football',
  'Konbini',
  'Food',
  'Rugby',
  'Cunnilingus',
  'Body Swapping',
  'Sadism',
  'Poker',
  'Centaur',
  'Memory Manipulation',
  'Guns',
  'Inseki',
  'Amputation',
  'Cyberpunk',
  'Dystopian',
  'Bisexual',
  'Alternate Universe',
  'Bondage',
  'Criminal Organization',
  'Cult',
  'Human Pet',
  'Superhero',
  'Firefighters',
  'Economics',
  'Achromatic',
  'Mating Press',
  'Basketball',
  'Asexual',
  'Squirting',
  'Seinen',
  'Parody',
  'Rural',
  'Rehabilitation',
  'Asphyxiation',
  'Crossdressing',
  'Bar',
  'Video Games',
  'Mermaid',
  'Tanks',
  'Primarily Male Cast',
  'Cervix Penetration',
  'Horticulture',
  'Philosophy',
  'Cheerleading',
  'Airsoft',
  'Writing',
  'Parenthood',
  'Threesome',
  'Mafia',
  'Restaurant',
  'Slapstick',
  'Indigenous Cultures',
  'Adoption',
  'Gods',
  'Flat Chest',
  'Polyamorous',
  'Elf',
  'Watersports',
  'Butler',
  'Space Opera',
  'Marriage',
  'Hip-hop Music',
  'CGI',
  'Office',
  'Mahjong',
  'Defloration',
  'Scissoring',
  'Pet Play',
  'Post-Apocalyptic',
  'Dancing',
  'Judo',
  'Villainess',
  'Modeling',
  'Kingdom Management',
  'Coastal',
  'Athletics',
  'Cumflation',
  'Facial',
  'Aliens',
  'Mixed Gender Harem',
  'Volleyball',
  'Espionage',
  'Metal Music',
  'Artificial Intelligence',
  'Masochism',
  'Mopeds',
  'Love Triangle',
  'Voyeur',
  'Female Protagonist',
  'Youkai',
  'Reverse Isekai',
  'Vampire',
  'Cycling',
  'Ancient China',
  'Twins',
  'Shoujo',
  'Survival',
  'Eco-Horror',
  'Urban Fantasy',
  'Football',
  'Torture',
  'Werewolf',
  'Snowscape',
  'Josei',
  'Body Image',
  'Suicide',
  'Ninja',
  'Animals',
  'Futanari',
  'Exorcism',
  'Demons',
  'Work',
  'Male Pregnancy',
  'Primarily Female Cast',
  'Aromantic',
  'Coming of Age',
  'Unrequited Love',
  'Travel',
  'Male Protagonist',
  'Scuba Diving',
  'Chuunibyou',
  'Manzai',
  'Trains',
  'Monster Girl',
  'Episodic',
  'Surfing',
  'Tsundere',
  'Ashikoki',
  'Classic Literature',
  'Educational',
  'Shrine Maiden',
  'Tennis',
  'Fairy',
  'Tragedy',
  'Handball',
  'Anti-Hero',
  'Lactation',
  'Slavery',
  'War',
  'Curses',
  'Real Robot',
  'Musical Theater',
  'Netorare',
  'Cute Girls Doing Cute Things',
  'Age Regression',
  'Witch',
  'Amnesia',
  'Satire',
  'Shimaidon',
  'Masturbation',
  'Sumata',
  'Anthropomorphism',
  'Terrorism',
  'Zoophilia',
  'Armpits',
  'Anal Sex',
  'Time Loop',
  'Femboy',
  'Triads',
  'Non-fiction',
  'Chibi',
  'Succubus',
  'Oyakodon',
  'Band',
  'Medieval',
  'Fishing',
  'Cannibalism',
  'Hair Pulling',
  'Time Manipulation',
  'Vocal Synth',
  'Alchemy',
  'Angels',
  'POV',
  'Cosmic Horror',
  'Estranged Family',
  'MILF',
  'Matriarchy',
  'Calligraphy',
  'Heterosexual',
  'Table Tennis',
  'Yandere',
  'Crime',
  'Large Breasts',
  'Environmental',
  'Battle Royale',
  'Ships',
  'Foreign',
  'Reincarnation',
  'Kaiju',
  'Assassins',
  'College',
  'Fellatio',
  'Necromancy',
  'Yuri',
  'Group Sex',
  'Hypersexuality',
  'Language Barrier',
  'Noir',
  'Kids',
  'Age Gap',
  'Drugs',
  'Police',
  'Zombie',
  'Golf',
  'Religion',
  'Military',
  'Rescue',
  'Deepthroat',
  'Nakadashi',
  'Virtual World',
  'Monster Boy',
  'Vikings',
  'Teacher',
  'Cowboys',
  'Dinosaurs',
  'Pregnancy',
  'Delinquents',
  'Acting',
  'DILF',
  'Erotic Piercings',
  'Ensemble Cast',
  'Dragons',
  'Wilderness',
  'Cosplay',
  'Board Game',
  'Male Harem',
  'Surreal Comedy',
  'Femdom',
  'Cyborg',
  'Fugitive',
  'Anthology',
  'Wrestling',
  'Steampunk',
  'Lacrosse',
  'Scat',
  'Full CGI',
  'Gender Bending',
  'Astronomy',
  'Female Harem',
  'Found Family',
  'Netorase',
  'Ahegao',
  'Gyaru',
  'No Dialogue',
  'Space',
  'Denpa',
  'Henshin',
  'Swapping ',
  'Cohabitation',
  'Nekomimi',
  'Aviation',
  'Class Struggle',
  'Motorcycles',
  'Exhibitionism',
  'Swordplay',
  'Makeup',
  'Circus',
  'Double Penetration',
  'Rimjob',
  'Sumo',
  'Conspiracy',
  'Shapeshifting',
  'Samurai',
  'Sweat',
  'Rape',
  'Meta',
  'Card Battle',
  'Desert',
  'E-Sports',
  'Prison',
  'Rakugo',
  'Primarily Animal Cast',
  'Fencing',
  'Cheating',
  'Cultivation',
  'Maids',
  'Jazz Music',
  'Impersonation',
  'Camping',
  'Ghost',
  'Pandemic',
  'Office Lady',
  'Prostitution',
  'Creature Taming',
  'Boxing',
  'School',
  'Politics',
  'Photography',
  'Veterinarian',
  'VTuber',
  'Kuudere',
  'LGBTQ+ Themes',
  'Inn',
  'Body Horror',
  'Martial Arts',
  'Tentacles',
  'Chimera',
  'Virginity',
  '4-koma',
  'Homeless',
  'Orphan',
  "Teens' Love",
  'Time Skip',
  'School Club',
  'Incest',
  'Omegaverse',
  'Medicine',
  'Ero Guro',
  'Gangs',
  'Fingering',
  'Dissociative Identities',
  'Biographical',
  'Crossover',
  'Handjob',
  'Cars',
  'Otaku Culture',
  'Fake Relationship',
  'Classical Music',
  'Royal Affairs',
  'Tomboy',
  'Historical',
  'Long Strip',
  'Hikikomori',
  'Boobjob',
  'Acrobatics',
  'Iyashikei',
  'Dungeon',
  'Mountaineering',
  'Mixed Media',
  'Badminton',
  'Robots',
  "Boys' Love",
  'Lost Civilization',
  'Mythology',
];
